# Generated by Django 5.2.4 on 2025-07-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Picked', 'Picked'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Customer.customer')),
            ],
        ),
    ]
